#!/bin/bash

make ${MAKE_J} && exit 0

if [ -x /usr/bin/find ] && [ -e ${ARCHROOT}/${5}/usr/bin/libtool ];then
  cp ${ARCHROOT}/${5}/usr/bin/libtool ./libtool-arch
  find . -name libtool |awk '{printf "cp libtool-arch %s\n", $1}' |sh
  make ${MAKE_J}
fi;
